# Generated by Django 4.2.4 on 2023-10-03 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_remove_categorias_fechacreacion_categorias_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=40)),
                ('apellidoPaterno', models.CharField(max_length=40)),
                ('apellidoMaterno', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='articulos',
            name='id_categoria',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.categorias'),
            preserve_default=False,
        ),
    ]
