# Generated by Django 4.2.4 on 2023-10-04 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('AppCoder', '0004_clientes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='grupo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
