# Generated by Django 4.2.4 on 2023-10-04 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_clientes_grupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientes',
            name='grupo',
        ),
    ]
