# Generated by Django 4.2.4 on 2023-10-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0008_articulos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulos',
            name='imagen',
            field=models.ImageField(blank=True, default='imagenes/sinimagen.png', null=True, upload_to='imagenes'),
        ),
    ]
