# Generated by Django 4.2.4 on 2023-10-07 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_alter_avatar_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioArticulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(max_length=40)),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.articulos')),
            ],
        ),
    ]
