# Generated by Django 4.2.4 on 2023-10-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0015_comentarioarticulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarioarticulos',
            name='comentario',
            field=models.CharField(max_length=255),
        ),
    ]
